### ISSUE TITLE
No module named 'pushbullet'

### ISSUE THREAD

**Issue by bgregos** [amhokies/Timetable-Stalker#1]
I get the following error when I try to run on my debian stretch system:
`Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from pushbullet.py import Pushbullet
ImportError: No module named 'pushbullet'`

At first I thought it was something to do with the dependencies, but those are all installing correctly for me.

**Comment by amhokies** [comment]
It seems you're missing the dependencies, so try running `pip3 install -r requirements.txt` if the command in the README isn't working for you.

**Comment by bgregos** [comment]
That worked, I was using python2's version of pip while running the script with python3. Thanks!
