### ISSUE TITLE
Add term selection via config file

### ISSUE THREAD

**Issue by bgregos** [amhokies/Timetable-Stalker#2]
Allow the user to select the term (fall/winter/etc...) and year via the config file, so the app doesn't need to be updated each term. 

I'd be willing to write a PR to add this functionality, if you think it's a useful addition.

**Comment by bgregos** [comment]
I'd be willing to write a PR to add this as well.

**Comment by amhokies** [comment]
Sounds like a good idea to me. Go for it!
